language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc g++ gfortran build-essential git wget linux-image-generic libopenblas-dev python-dev python-pip python-nose python-numpy python-scipy
install:
  - "pip install -r req-travis.txt"
# command to run tests
script: nosetests